[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "versioneer"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning",
    "ignore:builtin type SwigPyObject has no __module__ attribute",
    "ignore:builtin type swigvarlink has no __module__ attribute"
]
