name: BuildGHPages

on:
  push:
    branches:
      - gh-pages-source

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python }}"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r docs/requirements.txt
    - name: Build docs
      shell: bash
      run: |
        pwd
        make clean html
        mv _build/html ${GITHUB_WORKSPACE}/..
        git clean -f
      working-directory: ./docs
    - name: Create gh-pages
      shell: bash
      run: |
        pwd
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git checkout --orphan gh-pages
        git reset --hard
        git remote add deploy "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        ls
        mv ${GITHUB_WORKSPACE}/../html/* .
        touch .nojekyll
        ls -la
        git add .
        git commit -am "Autobuild of gh-pages"
        git push -u deploy gh-pages --force
